### PR TITLE
JS Initial Commit

### PR DESCRIPTION
**Pull request by ClarenceL**
This is the skeleton / npm package.json for the wrapper JS module

- also moved `demo` into `demo/demo.js`

I created a test external repo that includes this, it builds the N-API module properly - https://github.com/ClarenceL/elastos-chat

`package.json` defines the main file as `js/index.js` which is an Elastos root class, my current idea is that this is a singleton with sub components for RT, carrier etc...

So for example calls would look like `Elastos.carrier.getIdByAddress` which is `ela_get_id_by_address`.

### CODE REVIEW

**Comment by ClarenceL** [comment]
Hi @kuit I think you're working on the N-API module? 

What's your opinion of making it a dependency of a wrapper JS library? An extra layer of abstraction may be nice, you only have to worry about implementing the core Carrier functions.

**Comment by kuit** [comment]
Hi,@ClarenceL
Yes, I'm working on the N-API. And coding a module of Node.js for Carrier API. 
1.NAPI is as part of Node.js itself. 
2.It is simple. 
3.It is like as the logic of JavaScript language.

**Comment by kevingzhang** [comment]
Any concern about future compatibility of N-API? Is it going to be the replacement of NaN?

**Comment by ClarenceL** [comment]
N-API might be even more compatible, Microsoft's new JS engine is likely going to be N-API compatible - this opens up potential partnerships with Microsoft which have more money to throw around

**Pull request merged**
